spring:
  application:
    name: seatsure

  datasource:
    url: jdbc:postgresql://localhost:5433/seatsure
    username: postgres
    password: K1ng0fSeas@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto-creates/updates tables from your entities — great for learning, we'll tighten this later
    show-sql: true        # prints every SQL query Hibernate runs — very useful while learning
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

jwt:
  secret: this-is-a-temporary-dev-secret-key-change-me-before-any-real-deployment-1234567890
  expiration-ms: 86400000   # 24 hours, in milliseconds

logging:
  level:
    org.hibernate.SQL: debug