spring:
  application:
    name: seatsure

  datasource:
    url: jdbc:postgresql://localhost:5433/seatsure
    username: postgres
    password: K1ng0fSeas@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update   # auto-creates/updates tables from your entities — great for learning, we'll tighten this later
    show-sql: true        # prints every SQL query Hibernate runs — very useful while learning
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug